<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VulnerableGroupsTableSeeder extends Seeder
{
    protected $data = [];
    
    /**
     * Get the data array
     */
    public function getData() {
        if (empty($this->data)) {
            $this->run();
        }
        return $this->data;
    }
    
    /**
     * Clean and validate a record
     */
    protected function cleanRecord(array $record): ?array
    {
        // Ensure required fields exist with defaults
        $required = [
            'serial_number' => '',
            'name' => 'Unknown',
            'identification_number' => '',
            'gender' => 'UNKNOWN',
            'address' => 'Unknown',
            'district' => 'Unknown',
            'disability_category' => 'UNKNOWN',
            'client_type' => 'UNKNOWN',
            'oku_status' => 'UNKNOWN',
            'age_group' => 'UNKNOWN',
            'parliament' => '',
            'dun' => '',
            'phone_number' => '',
            'parliament_dun_code' => '',
            'prb_serial_number' => '',
            'installation_status' => 'BERJAYA',
            'latitude' => null,
            'longitude' => null,
        ];
        
        // Merge with defaults
        $record = array_merge($required, $record);
        
        // Clean fields
        $clean = [];
        
        // Serial number
        $clean['serial_number'] = substr($record['serial_number'], 0, 20);
        
        // Name
        $clean['name'] = substr($record['name'], 0, 100);
        
        // Identification number
        $clean['identification_number'] = substr($record['identification_number'], 0, 20);
        
        // Gender
        $clean['gender'] = in_array(strtoupper($record['gender']), ['LELAKI', 'PEREMPUAN']) 
            ? strtoupper($record['gender']) 
            : 'LELAKI'; // Default value
            
        // Address
        $clean['address'] = $record['address'];
        
        // District
        $clean['district'] = substr($record['district'], 0, 50);
        
        // Parliament (nullable)
        $clean['parliament'] = isset($record['parliament']) && $record['parliament'] !== '' 
            ? substr($record['parliament'], 0, 50) 
            : null;
            
        // DUN (nullable)
        $clean['dun'] = isset($record['dun']) && $record['dun'] !== '' 
            ? substr($record['dun'], 0, 50) 
            : null;
            
        // Phone number (nullable)
        $clean['phone_number'] = isset($record['phone_number']) && $record['phone_number'] !== '' 
            ? substr($record['phone_number'], 0, 20) 
            : null;
            
        // Disability category
        $validCategories = [
            'TERBARING', 'BERTONGKAT', 'BERKERUSI RODA', 'BOLEH BERJALAN', 'BUTA', 
            'OKU (LAIN-LAIN KEUPAYAAN)', 'WARGA EMAS (PENYAKIT 3 SERANGKAI)', 
            'WARGA EMAS (PENYAKIT DARAH TINGGI)', 'WARGA EMAS', 'ISTERI TERLANTAR', 
            'WARGA EMAS (TINGGAL BERDUA DENGAN ISTERI)', 'WARGA EMAS (11 ORANG)', 
            'WARGA EMAS (8 ORANG)', 'WARGA EMAS (4 ORANG)', 'WARGA EMAS (2 ORANG)', 
            'BERKERUSI RODA BOLEH BERJALAN', '-'
        ];
        
        $clean['disability_category'] = in_array(strtoupper($record['disability_category']), $validCategories)
            ? strtoupper($record['disability_category'])
            : '-';
            
        // Client type
        $clean['client_type'] = in_array(strtoupper($record['client_type']), ['JKM', 'HOSPITAL', 'KOMUNITI', 'SUKARELA'])
            ? strtoupper($record['client_type'])
            : 'JKM'; // Default value
            
        // OKU status - ensure it's either 'YA' or 'TIDAK'
        $okuStatus = strtoupper(trim($record['oku_status']));
        $clean['oku_status'] = ($okuStatus === 'YA' || 
                               stripos($record['oku_status'], 'OKU') !== false ||
                               stripos($record['oku_status'], 'ORANG KURANG UPAYA') !== false)
            ? 'YA'
            : 'TIDAK';
            
        // Age group
        $clean['age_group'] = in_array(strtoupper($record['age_group']), ['KANAK-KANAK', 'DEWASA', 'WARGA EMAS'])
            ? strtoupper($record['age_group'])
            : 'DEWASA'; // Default value
            
        // Parliament/DUN code (nullable)
        $clean['parliament_dun_code'] = isset($record['parliament_dun_code']) && $record['parliament_dun_code'] !== '' 
            ? substr($record['parliament_dun_code'], 0, 20) 
            : null;
            
        // PRB serial number (nullable)
        $clean['prb_serial_number'] = isset($record['prb_serial_number']) && $record['prb_serial_number'] !== '' 
            ? substr($record['prb_serial_number'], 0, 20) 
            : null;
            
        // Installation status
        $clean['installation_status'] = in_array(strtoupper($record['installation_status'] ?? 'BERJAYA'), ['BERJAYA', 'TIDAK'])
            ? strtoupper($record['installation_status'])
            : 'BERJAYA'; // Default value
            
        // Latitude and longitude
        $clean['latitude'] = is_numeric($record['latitude'] ?? null) ? (float)$record['latitude'] : null;
        $clean['longitude'] = is_numeric($record['longitude'] ?? null) ? (float)$record['longitude'] : null;
        
        // Notes (nullable)
        $clean['notes'] = $record['notes'] ?? null;
        
        // Installation date (nullable)
        $clean['installation_date'] = isset($record['installation_date']) && $record['installation_date'] !== ''
            ? $record['installation_date']
            : null;
            
        // Timestamps
        $clean['created_at'] = now();
        $clean['updated_at'] = now();
        
        return $clean;
    }
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Function to create record with common fields
        $createRecord = function($data) {
            return array_merge([
                'created_at' => now(),
                'updated_at' => now(),
            ], $data);
        };

        // Batu Pahat records
        $batuPahatData = [
            $createRecord([
                'serial_number' => 'BP001',
                'name' => 'TAIB BIN BABA',
                'identification_number' => '441121-01-5385',
                'gender' => 'LELAKI',
                'address' => 'KAMPUNG SRI BENGKAL, MUKIM 6, 83300 SRI GADING, BATU PAHAT, JOHOR DARUL TA\'ZIM',
                'district' => 'BATU PAHAT',
                'parliament' => 'SRI GADING',
                'dun' => 'PARIT YAANI',
                'phone_number' => '017-7257723',
                'disability_category' => 'TERBARING',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P149N21',
                'prb_serial_number' => 'JWL1001',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.89228,
                'longitude' => 103.016432,
            ]),
            $createRecord([
                'serial_number' => 'BP002',
                'name' => 'UTONG BIN NASIR',
                'identification_number' => '541107-01-5723',
                'gender' => 'LELAKI',
                'address' => '125, KAMPUNG SRI BENGKAL, MUKIM 6, 83300 SRI GADING, BATU PAHAT, JOHOR DARUL TA\'ZIM',
                'district' => 'BATU PAHAT',
                'parliament' => 'SRI GADING',
                'dun' => 'PARIT YAANI',
                'phone_number' => '019-7394497',
                'disability_category' => 'TERBARING',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P149N21',
                'prb_serial_number' => 'JWL1002',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.905367,
                'longitude' => 103.02815,
            ]),
            $createRecord([
                'serial_number' => 'BP003',
                'name' => 'HAJI MD LAJIS BIN MORID',
                'identification_number' => '300621-01-5307',
                'gender' => 'LELAKI',
                'address' => '108, KAMPUNG SRI BENGKAL, MUKIM 6, 83300 SRI GADING, BATU PAHAT, JOHOR DARUL TA\'ZIM',
                'district' => 'BATU PAHAT',
                'parliament' => 'SRI GADING',
                'dun' => 'PARIT YAANI',
                'phone_number' => '010-2016576',
                'disability_category' => 'TERBARING',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P149N21',
                'prb_serial_number' => 'JWL1003',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.918216,
                'longitude' => 103.033068,
            ]),
            $createRecord([
                'serial_number' => 'BP004',
                'name' => 'MASRIAH BTE REMIN',
                'identification_number' => '361120-01-5658',
                'gender' => 'PEREMPUAN',
                'address' => '10, KAMPUNG SRI BENGKAL, MUKIM 6, 83300 SRI GADING, BATU PAHAT, JOHOR DARUL TA\'ZIM',
                'district' => 'BATU PAHAT',
                'parliament' => 'SRI GADING',
                'dun' => 'PARIT YAANI',
                'phone_number' => '016-7426314',
                'disability_category' => 'TERBARING',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P149N21',
                'prb_serial_number' => 'JWP1004',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.882497,
                'longitude' => 103.015754,
            ]),
            $createRecord([
                'serial_number' => 'BP005',
                'name' => 'JAHARAH BINTI TUKIRAN',
                'identification_number' => '660228-01-6528',
                'gender' => 'PEREMPUAN',
                'address' => 'KAMPUNG PARIT SURATMAN, PARIT YAANI, 83710 YONG PENG, JOHOR DARUL TA\'ZIM',
                'district' => 'BATU PAHAT',
                'parliament' => 'SRI GADING',
                'dun' => 'PARIT YAANI',
                'phone_number' => '011-69715790',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'YA',
                'age_group' => 'DEWASA',
                'parliament_dun_code' => 'P149N21',
                'prb_serial_number' => 'JDP4006',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.94566,
                'longitude' => 103.01120,
            ]),
            $createRecord([
                'serial_number' => 'BP006',
                'name' => 'SIAM BIN SARLAN',
                'identification_number' => '620227-01-5969',
                'gender' => 'LELAKI',
                'address' => 'KAMPUNG PARIT SURATMAN, PARIT YAANI, 83710 YONG PENG, JOHOR DARUL TA\'ZIM',
                'district' => 'BATU PAHAT',
                'parliament' => 'SRI GADING',
                'dun' => 'PARIT YAANI',
                'phone_number' => '011-53420171',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'YA',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P149N21',
                'prb_serial_number' => 'JWL4007',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.94136,
                'longitude' => 103.01672,
            ]),
            $createRecord([
                'serial_number' => 'BP007',
                'name' => 'ARSAD BIN ADNAN',
                'identification_number' => '580523-01-5249',
                'gender' => 'LELAKI',
                'address' => 'KAMPUNG PARIT SURATMAN, PARIT YAANI, 83710 YONG PENG, JOHOR DARUL TA\'ZIM',
                'district' => 'BATU PAHAT',
                'parliament' => 'SRI GADING',
                'dun' => 'PARIT YAANI',
                'phone_number' => '019-7412671',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'YA',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P149N21',
                'prb_serial_number' => 'JWL4008',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.94081,
                'longitude' => 103.02551,
            ]),
            $createRecord([
                'serial_number' => 'BP008',
                'name' => 'MUJILAH BINTI OMAR',
                'identification_number' => '341026-01-5128',
                'gender' => 'PEREMPUAN',
                'address' => 'KAMPUNG PARIT SURATMAN, PARIT YAANI, 83710 YONG PENG, JOHOR DARUL TA\'ZIM',
                'district' => 'BATU PAHAT',
                'parliament' => 'SRI GADING',
                'dun' => 'PARIT YAANI',
                'phone_number' => '019-7668915',
                'disability_category' => 'TERBARING',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P149N21',
                'prb_serial_number' => 'JWP1009',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.94322,
                'longitude' => 103.00794,
            ]),
            $createRecord([
                'serial_number' => 'BP009',
                'name' => 'MOHD SAID BIN SABTU',
                'identification_number' => '561222-01-6391',
                'gender' => 'LELAKI',
                'address' => 'KAMPUNG PARIT SURATMAN, PARIT YAANI, 83710 YONG PENG, JOHOR DARUL TA\'ZIM',
                'district' => 'BATU PAHAT',
                'parliament' => 'SRI GADING',
                'dun' => 'PARIT YAANI',
                'phone_number' => '010-5310116',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'YA',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P149N21',
                'prb_serial_number' => 'JWL4010',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.94268,
                'longitude' => 103.01510,
            ]),
            $createRecord([
                'serial_number' => 'BP010',
                'name' => 'ZORIAH BINTI IBRAHIM',
                'identification_number' => '790228-01-5006',
                'gender' => 'PEREMPUAN',
                'address' => 'KAMPUNG PARIT LINTANG LUAR, PARIT YAANI, 83710 YONG PENG, JOHOR DARUL TA\'ZIM',
                'district' => 'BATU PAHAT',
                'parliament' => 'SRI GADING',
                'dun' => 'PARIT YAANI',
                'phone_number' => '017-7003211',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'YA',
                'age_group' => 'DEWASA',
                'parliament_dun_code' => 'P149N21',
                'prb_serial_number' => 'JDP4011',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.94274,
                'longitude' => 103.02394,
            ]),
            $createRecord([
                'serial_number' => 'BP011',
                'name' => 'AHMAD BIN ABDULLAH',
                'identification_number' => '371220-01-5427',
                'gender' => 'LELAKI',
                'address' => 'KAMPUNG PARIT SURATMAN, PARIT YAANI, 83710 YONG PENG, JOHOR DARUL TA\'ZIM',
                'district' => 'BATU PAHAT',
                'parliament' => 'SRI GADING',
                'dun' => 'PARIT YAANI',
                'phone_number' => '012-7468047',
                'disability_category' => 'BERTONGKAT',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P149N21',
                'prb_serial_number' => 'JWL2012',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.939309,
                'longitude' => 103.006730,
            ]),
            $createRecord([
                'serial_number' => 'BP012',
                'name' => 'FATIMAH BINTI HAMID@ABD HAMID',
                'identification_number' => '4703080-01-5388',
                'gender' => 'PEREMPUAN',
                'address' => 'KAMPUNG PARIT SURATMAN, PARIT YAANI, 83710 YONG PENG, JOHOR DARUL TA\'ZIM',
                'district' => 'BATU PAHAT',
                'parliament' => 'SRI GADING',
                'dun' => 'PARIT YAANI',
                'phone_number' => '011-36714760',
                'disability_category' => 'BERTONGKAT',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P149N21',
                'prb_serial_number' => 'JWP2013',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.93504,
                'longitude' => 103.00595,
            ]),
            $createRecord([
                'serial_number' => 'BP013',
                'name' => 'HAMIMAH BINTI SARLAN',
                'identification_number' => '591115-01-5788',
                'gender' => 'PEREMPUAN',
                'address' => 'KAMPUNG PARIT SURATMAN, PARIT YAANI, 83710 YONG PENG, JOHOR DARUL TA\'ZIM',
                'district' => 'BATU PAHAT',
                'parliament' => 'SRI GADING',
                'dun' => 'PARIT YAANI',
                'phone_number' => '018-3943538',
                'disability_category' => 'BERTONGKAT',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P149N21',
                'prb_serial_number' => 'JWP2014',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.94136,
                'longitude' => 103.01672,
            ]),
            $createRecord([
                'serial_number' => 'BP014',
                'name' => 'KARNO BIN SAIMON',
                'identification_number' => '500704-01-5421',
                'gender' => 'LELAKI',
                'address' => 'KAMPUNG PARIT SURATMAN, PARIT YAANI, 83710 YONG PENG, JOHOR DARUL TA\'ZIM',
                'district' => 'BATU PAHAT',
                'parliament' => 'SRI GADING',
                'dun' => 'PARIT YAANI',
                'phone_number' => '019-7816085',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'YA',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P149N21',
                'prb_serial_number' => 'JWL2015',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.93980,
                'longitude' => 103.01324,
            ]),
            $createRecord([
                'serial_number' => 'BP015',
                'name' => 'SAADAH BINTI JAMAAIN@JEMAIN',
                'identification_number' => '460104-01-5756',
                'gender' => 'PEREMPUAN',
                'address' => 'KAMPUNG PARIT SURATMAN, PARIT YAANI, 83710 YONG PENG, JOHOR DARUL TA\'ZIM',
                'district' => 'BATU PAHAT',
                'parliament' => 'SRI GADING',
                'dun' => 'PARIT YAANI',
                'phone_number' => '011-59022627',
                'disability_category' => 'BERKERUSI RODA',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P149N21',
                'prb_serial_number' => 'JWP3016',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.94098,
                'longitude' => 103.01716,
            ]),
            $createRecord([
                'serial_number' => 'BP016',
                'name' => 'SALAMAH BINTI TAIRAN',
                'identification_number' => '371011-01-5666',
                'gender' => 'PEREMPUAN',
                'address' => 'KAMPUNG PARIT SURATMAN, PARIT YAANI, 83710 YONG PENG, JOHOR DARUL TA\'ZIM',
                'district' => 'BATU PAHAT',
                'parliament' => 'SRI GADING',
                'dun' => 'PARIT YAANI',
                'phone_number' => '017-7046234',
                'disability_category' => 'BERTONGKAT',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P149N21',
                'prb_serial_number' => 'JWP2017',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.94175,
                'longitude' => 103.01540,
            ]),
            $createRecord([
                'serial_number' => 'BP017',
                'name' => 'NURUL HADI BIN NOOR HALIM',
                'identification_number' => '980122-01-7123',
                'gender' => 'LELAKI',
                'address' => 'KAMPUNG PARIT SURATMAN, PARIT YAANI, 83710 YONG PENG, JOHOR DARUL TA\'ZIM',
                'district' => 'BATU PAHAT',
                'parliament' => 'SRI GADING',
                'dun' => 'PARIT YAANI',
                'phone_number' => '013-7428816',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'YA',
                'age_group' => 'DEWASA',
                'parliament_dun_code' => 'P149N21',
                'prb_serial_number' => 'JDL4018',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.94311,
                'longitude' => 103.01061,
            ]),
            $createRecord([
                'serial_number' => 'BP018',
                'name' => 'SAMINAH BINTI WARSAN',
                'identification_number' => '380322-01-5174',
                'gender' => 'PEREMPUAN',
                'address' => 'KAMPUNG PARIT YAANI, 83710 YONG PENG, JOHOR DARUL TA\'ZIM',
                'district' => 'BATU PAHAT',
                'parliament' => 'SRI GADING',
                'dun' => 'PARIT YAANI',
                'phone_number' => '019-7412671',
                'disability_category' => 'BERTONGKAT',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P149N21',
                'prb_serial_number' => 'JWP2019',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.94274,
                'longitude' => 103.02394,
            ]),
            $createRecord([
                'serial_number' => 'BP019',
                'name' => 'SANIAH BINTI DARMON',
                'identification_number' => '470401-01-5796',
                'gender' => 'PEREMPUAN',
                'address' => 'KAMPUNG PARIT SURATMAN, PARIT YAANI, 83710 YONG PENG, JOHOR DARUL TA\'ZIM',
                'district' => 'BATU PAHAT',
                'parliament' => 'SRI GADING',
                'dun' => 'PARIT YAANI',
                'phone_number' => '017-7211023',
                'disability_category' => 'BERKERUSI RODA',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P149N21',
                'prb_serial_number' => 'JWP3020',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.94042,
                'longitude' => 103.01734,
            ]),
            $createRecord([
                'serial_number' => 'BP020',
                'name' => 'MARIAM BINTI RADIMAN',
                'identification_number' => '390721-01-5090',
                'gender' => 'PEREMPUAN',
                'address' => 'PARIT YAANI TENGAH, PARIT YAANI, 83710 YONG PENG, JOHOR DARUL TA\'ZIM',
                'district' => 'BATU PAHAT',
                'parliament' => 'SRI GADING',
                'dun' => 'PARIT YAANI',
                'phone_number' => '07-4847259',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P149N21',
                'prb_serial_number' => 'JWP4021',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.9115835,
                'longitude' => 103.0193376,
            ]),
            $createRecord([
                'serial_number' => 'BP021',
                'name' => 'ROSLAN BIN BINGAN',
                'identification_number' => '660614-01-5615',
                'gender' => 'LELAKI',
                'address' => 'PARIT SENAH, PARIT YAANI, 83710 YONG PENG, JOHOR DARUL TA\'ZIM',
                'district' => 'BATU PAHAT',
                'parliament' => 'SRI GADING',
                'dun' => 'PARIT YAANI',
                'phone_number' => '07-4847259',
                'disability_category' => 'BUTA',
                'client_type' => 'JKM',
                'oku_status' => 'YA',
                'age_group' => 'DEWASA',
                'parliament_dun_code' => 'P149N21',
                'prb_serial_number' => 'JDL5022',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.92670,
                'longitude' => 103.01557,
            ]),
            $createRecord([
                'serial_number' => 'BP022',
                'name' => 'MUHAMMAD FUAD BIN ROSLAN',
                'identification_number' => '980703-01-6575',
                'gender' => 'LELAKI',
                'address' => 'PARIT YAANI LAUT, PARIT YAANI, 83710 YONG PENG, JOHOR DARUL TA\'ZIM',
                'district' => 'BATU PAHAT',
                'parliament' => 'SRI GADING',
                'dun' => 'PARIT YAANI',
                'phone_number' => '018-7896054',
                'disability_category' => 'TERBARING',
                'client_type' => 'JKM',
                'oku_status' => 'YA',
                'age_group' => 'DEWASA',
                'parliament_dun_code' => 'P149N21',
                'prb_serial_number' => 'JDL5024',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.88789,
                'longitude' => 103.01248,
            ]),
            $createRecord([
                'serial_number' => 'BP023',
                'name' => 'TASLIMAH BTE BASAR',
                'identification_number' => '410701-01-5670',
                'gender' => 'PEREMPUAN',
                'address' => 'PARIT YAANI TENGAH, PARIT YAANI, 83710 YONG PENG, JOHOR DARUL TA\'ZIM',
                'district' => 'BATU PAHAT',
                'parliament' => 'SRI GADING',
                'dun' => 'PARIT YAANI',
                'phone_number' => '07-4847259',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P149N21',
                'prb_serial_number' => 'JWP4025',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.91385,
                'longitude' => 103.02028,
            ]),
            $createRecord([
                'serial_number' => 'BP024',
                'name' => 'MOHD KAMIS B KAMIJO',
                'identification_number' => '490411-01-5931',
                'gender' => 'LELAKI',
                'address' => 'PARIT YAANI TENGAH, PARIT YAANI, 83710 YONG PENG, JOHOR DARUL TA\'ZIM',
                'district' => 'BATU PAHAT',
                'parliament' => 'SRI GADING',
                'dun' => 'PARIT YAANI',
                'phone_number' => '07-4847259',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P149N21',
                'prb_serial_number' => 'JWL4026',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.92564,
                'longitude' => 103.02062,
            ]),
            $createRecord([
                'serial_number' => 'BP025',
                'name' => 'NALIMAH BINTI MOHD TAIB',
                'identification_number' => '660121-01-5414',
                'gender' => 'PEREMPUAN',
                'address' => 'POS 5, KAMPUNG PARIT ISMAIL, MUKIM 6, 83710 SRI GADING, BATU PAHAT, JOHOR DARUL TA\'ZIM',
                'district' => 'BATU PAHAT',
                'parliament' => 'SRI GADING',
                'dun' => 'PARIT YAANI',
                'phone_number' => '016-2966044',
                'disability_category' => 'BERKERUSI RODA',
                'client_type' => 'JKM',
                'oku_status' => 'YA',
                'age_group' => 'DEWASA',
                'parliament_dun_code' => 'P149N21',
                'prb_serial_number' => 'JDP3027',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.88172,
                'longitude' => 103.02214,
            ]),
            $createRecord([
                'serial_number' => 'BP026',
                'name' => 'MASIRAH BINTI KASSIM',
                'identification_number' => '530623-01-5988',
                'gender' => 'PEREMPUAN',
                'address' => 'POS 26, KAMPUNG PARIT ISMAIL, MUKIM 6, 83710 SRI GADING, BATU PAHAT, JOHOR DARUL TA\'ZIM',
                'district' => 'BATU PAHAT',
                'parliament' => 'SRI GADING',
                'dun' => 'PARIT YAANI',
                'phone_number' => '017-8807002',
                'disability_category' => 'BERTONGKAT',
                'client_type' => 'JKM',
                'oku_status' => 'YA',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P149N21',
                'prb_serial_number' => 'JWP2028',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.915552,
                'longitude' => 103.037689,
            ]),
            $createRecord([
                'serial_number' => 'BP027',
                'name' => 'SAMIAH BINTI MOHD RAJI',
                'identification_number' => '430410-01-5118',
                'gender' => 'PEREMPUAN',
                'address' => 'POS 10, KAMPUNG PARIT ISMAIL, MUKIM 6, 83710 SRI GADING, BATU PAHAT, JOHOR DARUL TA\'ZIM',
                'district' => 'BATU PAHAT',
                'parliament' => 'SRI GADING',
                'dun' => 'PARIT YAANI',
                'phone_number' => '010-6679237',
                'disability_category' => 'BERKERUSI RODA',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P149N21',
                'prb_serial_number' => 'JWP3030',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.90503,
                'longitude' => 103.03263,
            ]),
            $createRecord([
                'serial_number' => 'BP028',
                'name' => 'SANIP BIN HJ NOR',
                'identification_number' => '380706-01-5325',
                'gender' => 'LELAKI',
                'address' => 'POS 7, KAMPUNG PARIT ISMAIL, MUKIM 6, 83710 SRI GADING, BATU PAHAT, JOHOR DARUL TA\'ZIM',
                'district' => 'BATU PAHAT',
                'parliament' => 'SRI GADING',
                'dun' => 'PARIT YAANI',
                'phone_number' => '013-7226227',
                'disability_category' => 'BERKERUSI RODA',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P149N21',
                'prb_serial_number' => 'JWL3031',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.90331,
                'longitude' => 103.03270,
            ]),
            $createRecord([
                'serial_number' => 'BP029',
                'name' => 'AHMAD SATAR BIN OTHMAN',
                'identification_number' => '650807-01-5065',
                'gender' => 'LELAKI',
                'address' => 'POS 8, KAMPUNG PARIT ISMAIL, MUKIM 6, 83710 SRI GADING, BATU PAHAT, JOHOR DARUL TA\'ZIM',
                'district' => 'BATU PAHAT',
                'parliament' => 'SRI GADING',
                'dun' => 'PARIT YAANI',
                'phone_number' => '013-6311848',
                'disability_category' => 'BERTONGKAT',
                'client_type' => 'JKM',
                'oku_status' => 'YA',
                'age_group' => 'DEWASA',
                'parliament_dun_code' => 'P149N21',
                'prb_serial_number' => 'JDL2033',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.90470,
                'longitude' => 103.03210,
            ]),
            $createRecord([
                'serial_number' => 'BP030',
                'name' => 'MOHAMAD BIN ALI',
                'identification_number' => '810722-01-5883',
                'gender' => 'LELAKI',
                'address' => 'KAMPUNG MOHD NOOR, PARIT YAANI, YONG PENG, JOHOR DARUL TA\'ZIM',
                'district' => 'BATU PAHAT',
                'parliament' => 'SRI GADING',
                'dun' => 'PARIT YAANI',
                'phone_number' => '012-7340806',
                'disability_category' => 'BERTONGKAT',
                'client_type' => 'JKM',
                'oku_status' => 'YA',
                'age_group' => 'DEWASA',
                'parliament_dun_code' => 'P149N21',
                'prb_serial_number' => 'JDL2034',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.95772,
                'longitude' => 102.94234,
            ]),
            $createRecord([
                'serial_number' => 'BP031',
                'name' => 'MIRAH BINTI KHAMIS',
                'identification_number' => '381108-01-5602',
                'gender' => 'PEREMPUAN',
                'address' => '47, KAMPUNG MOHD NOOR, PARIT YAANI, YONG PENG, JOHOR DARUL TA\'ZIM',
                'district' => 'BATU PAHAT',
                'parliament' => 'SRI GADING',
                'dun' => 'PARIT YAANI',
                'phone_number' => '013-7102662',
                'disability_category' => 'TERBARING',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P149N21',
                'prb_serial_number' => 'JWP1035',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.9560986,
                'longitude' => 102.9447072,
            ]),
            $createRecord([
                'serial_number' => 'BP032',
                'name' => 'SANIFAH BINTI SABAR',
                'identification_number' => '561124-01-5870',
                'gender' => 'PEREMPUAN',
                'address' => 'KAMPUNG MOHD NOOR, PARIT YAANI, YONG PENG, JOHOR DARUL TA\'ZIM',
                'district' => 'BATU PAHAT',
                'parliament' => 'SRI GADING',
                'dun' => 'PARIT YAANI',
                'phone_number' => '017-7885313',
                'disability_category' => 'TERBARING',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P149N21',
                'prb_serial_number' => 'JWP1036',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.95651,
                'longitude' => 102.94428,
            ]),
            $createRecord([
                'serial_number' => 'BP033',
                'name' => 'WOOK BINTI ESAH',
                'identification_number' => '330821-01-5106',
                'gender' => 'PEREMPUAN',
                'address' => '50, KAMPUNG MOHD NOOR, PARIT YAANI, YONG PENG, JOHOR DARUL TA\'ZIM',
                'district' => 'BATU PAHAT',
                'parliament' => 'SRI GADING',
                'dun' => 'PARIT YAANI',
                'phone_number' => '019-7100002',
                'disability_category' => 'BERTONGKAT',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P149N21',
                'prb_serial_number' => 'JWP2037',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.9550025,
                'longitude' => 102.9460352,
            ]),
            $createRecord([
                'serial_number' => 'BP034',
                'name' => 'ROHANA BINTI KASIM',
                'identification_number' => '740728-01-6450',
                'gender' => 'PEREMPUAN',
                'address' => 'TL 29/24, KAMPUNG MOHD NOOR, PARIT YAANI, YONG PENG, JOHOR DARUL TA\'ZIM',
                'district' => 'BATU PAHAT',
                'parliament' => 'SRI GADING',
                'dun' => 'PARIT YAANI',
                'phone_number' => '017-7710370',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'DEWASA',
                'parliament_dun_code' => 'P149N21',
                'prb_serial_number' => 'JDP4038',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.9513776,
                'longitude' => 102.9530116,
            ]),
            $createRecord([
                'serial_number' => 'BP035',
                'name' => 'SITI NGAISAH BINTI SAIDI',
                'identification_number' => '420210-01-5050',
                'gender' => 'PEREMPUAN',
                'address' => '54, KAMPUNG MOHD NOOR, PARIT YAANI, YONG PENG, JOHOR DARUL TA\'ZIM',
                'district' => 'BATU PAHAT',
                'parliament' => 'SRI GADING',
                'dun' => 'PARIT YAANI',
                'phone_number' => '013-9711766',
                'disability_category' => 'BERTONGKAT',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P149N21',
                'prb_serial_number' => 'JWP2039',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.9520702,
                'longitude' => 102.9490413,
            ]),
            $createRecord([
                'serial_number' => 'BP036',
                'name' => 'MUNAH SEJU',
                'identification_number' => '380418-01-5590',
                'gender' => 'PEREMPUAN',
                'address' => 'PARIT YOB DARAT, PARIT YAANI, YONG PENG, JOHOR DARUL TA\'ZIM',
                'district' => 'BATU PAHAT',
                'parliament' => 'SRI GADING',
                'dun' => 'PARIT YAANI',
                'phone_number' => '019-7484754',
                'disability_category' => 'TERBARING',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P149N21',
                'prb_serial_number' => 'JWP1040',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.93985,
                'longitude' => 103.04149,
            ]),
        ];


        // Segamat records
        $segamatData = [
            $createRecord([
                'serial_number' => 'SG001',
                'name' => 'KIAH BT ATAN',
                'identification_number' => '370420-01-5574',
                'gender' => 'PEREMPUAN',
                'address' => 'NO 109 KAMPUNG SPANG LOI BATU ANAM',
                'district' => 'SEGAMAT',
                'parliament' => 'BULOH KASAP',
                'dun' => 'BULOH KASAP',
                'phone_number' => '012-7563251',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P140N01',
                'prb_serial_number' => 'JWP4001',
                'installation_status' => 'BERJAYA',
                'latitude' => 2.605064829,
                'longitude' => 102.7108414,
            ]),
            $createRecord([
                'serial_number' => 'SG002',
                'name' => 'PATIMAH BINTI SALIH',
                'identification_number' => '470617-01-5832',
                'gender' => 'PEREMPUAN',
                'address' => 'NO 90 KAMPUNG SPANG LOI',
                'district' => 'SEGAMAT',
                'parliament' => 'BULOH KASAP',
                'dun' => 'BULOH KASAP',
                'phone_number' => '012-7791445',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P140N01',
                'prb_serial_number' => 'JWP4002',
                'installation_status' => 'BERJAYA',
                'latitude' => 2.511222997,
                'longitude' => 102.8157977,
            ]),
            $createRecord([
                'serial_number' => 'SG003',
                'name' => 'ONN BIN MD WAZALI',
                'identification_number' => '711222-01-6149',
                'gender' => 'LELAKI',
                'address' => 'NO 59 KAMPUNG SPANG LOI SEGAMAT',
                'district' => 'SEGAMAT',
                'parliament' => 'BULOH KASAP',
                'dun' => 'BULOH KASAP',
                'phone_number' => '017-7274531',
                'disability_category' => 'TERBARING',
                'client_type' => 'JKM',
                'oku_status' => 'YA',
                'age_group' => 'DEWASA',
                'parliament_dun_code' => 'P140N01',
                'prb_serial_number' => 'JDL1003',
                'installation_status' => 'BERJAYA',
                'latitude' => 2.64603017,
                'longitude' => 102.7563283,
            ]),
            $createRecord([
                'serial_number' => 'SG004',
                'name' => 'AZIZAH BINTI JANTAN',
                'identification_number' => '570606-01-6176',
                'gender' => 'PEREMPUAN',
                'address' => 'NO 10 KAMPUNG SPANG LOI BATU ANAM',
                'district' => 'SEGAMAT',
                'parliament' => 'BULOH KASAP',
                'dun' => 'BULOH KASAP',
                'phone_number' => '019-7364952',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P140N01',
                'prb_serial_number' => 'JWP4005',
                'installation_status' => 'BERJAYA',
                'latitude' => 2.647733576,
                'longitude' => 102.7570765,
            ]),
            $createRecord([
                'serial_number' => 'SG005',
                'name' => 'MUHAMMAD ASMIRUL BIN ABDULLAH',
                'identification_number' => '970225-14-6631',
                'gender' => 'LELAKI',
                'address' => 'NO 88 JALAN MUHAMMAD KAMPUNG SPANG LOI85100 BATU ANAM SEGAMAT JOHOR',
                'district' => 'SEGAMAT',
                'parliament' => 'BULOH KASAP',
                'dun' => 'BULOH KASAP',
                'phone_number' => '018-7738749',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'YA',
                'age_group' => 'DEWASA',
                'parliament_dun_code' => 'P140N01',
                'prb_serial_number' => 'JWP4006',
                'installation_status' => 'BERJAYA',
                'latitude' => 2.578627442,
                'longitude' => 102.7073952,
            ]),
            $createRecord([
                'serial_number' => 'SG006',
                'name' => 'SELAMAT BIN AHMAD',
                'identification_number' => '710404-71-5157',
                'gender' => 'LELAKI',
                'address' => 'LOT 2049, JALAN SAHALKAMPUNG SPANG LOI',
                'district' => 'SEGAMAT',
                'parliament' => 'BULOH KASAP',
                'dun' => 'BULOH KASAP',
                'phone_number' => '018-7940887',
                'disability_category' => 'BERKERUSI RODA',
                'client_type' => 'JKM',
                'oku_status' => 'YA',
                'age_group' => 'DEWASA',
                'parliament_dun_code' => 'P140N01',
                'prb_serial_number' => 'JDL3010',
                'installation_status' => 'BERJAYA',
                'latitude' => 2.504180742,
                'longitude' => 102.8248363,
            ]),
            $createRecord([
                'serial_number' => 'SG007',
                'name' => 'MASROM BINTI NOH',
                'identification_number' => '630409-01-5424',
                'gender' => 'PEREMPUAN',
                'address' => 'NO 75A JALAN SAHALKAMPUNG SPANG LOI',
                'district' => 'SEGAMAT',
                'parliament' => 'BULOH KASAP',
                'dun' => 'BULOH KASAP',
                'phone_number' => '012-7682064',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P140N01',
                'prb_serial_number' => 'JWP4012',
                'installation_status' => 'BERJAYA',
                'latitude' => 2.504095017,
                'longitude' => 102.8247703,
            ]),
            $createRecord([
                'serial_number' => 'SG008',
                'name' => 'GAYAH BINTI SENTOL',
                'identification_number' => '270426-01-5008',
                'gender' => 'PEREMPUAN',
                'address' => 'NO 143 KAMPUNG SPANG LOI',
                'district' => 'SEGAMAT',
                'parliament' => 'BULOH KASAP',
                'dun' => 'BULOH KASAP',
                'phone_number' => '014-9197347',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P140N01',
                'prb_serial_number' => 'JWP4013',
                'installation_status' => 'BERJAYA',
                'latitude' => 2.646648379,
                'longitude' => 102.7563619,
            ]),
            $createRecord([
                'serial_number' => 'SG009',
                'name' => 'MOHAMMAD NOH BIN SUDIN',
                'identification_number' => '810706-01-6149',
                'gender' => 'LELAKI',
                'address' => 'NO 8 JALAN HASSAN KAMPUNG SPANG LOI',
                'district' => 'SEGAMAT',
                'parliament' => 'BULOH KASAP',
                'dun' => 'BULOH KASAP',
                'phone_number' => '016-4938604',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'YA',
                'age_group' => 'DEWASA',
                'parliament_dun_code' => 'P140N01',
                'prb_serial_number' => 'JDL4015',
                'installation_status' => 'BERJAYA',
                'latitude' => 2.526092765,
                'longitude' => 102.8168084,
            ]),
            $createRecord([
                'serial_number' => 'SG010',
                'name' => 'GAYAH BINTI MOHD SAP',
                'identification_number' => '350426-01-5278',
                'gender' => 'PEREMPUAN',
                'address' => 'NO 47 KAMPUNG SPANG LOI',
                'district' => 'SEGAMAT',
                'parliament' => 'BULOH KASAP',
                'dun' => 'BULOH KASAP',
                'phone_number' => '014-6298424',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P140N01',
                'prb_serial_number' => 'JWP4017',
                'installation_status' => 'BERJAYA',
                'latitude' => 2.646776537,
                'longitude' => 102.7560357,
            ]),
            $createRecord([
                'serial_number' => 'SG011',
                'name' => 'LIJAH BINTI SENGAH',
                'identification_number' => '480120-01-5860',
                'gender' => 'PEREMPUAN',
                'address' => 'NO 99 KAMPUNG SPANG LOI',
                'district' => 'SEGAMAT',
                'parliament' => 'BULOH KASAP',
                'dun' => 'BULOH KASAP',
                'phone_number' => '010-6681699',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P140N01',
                'prb_serial_number' => 'JWP4018',
                'installation_status' => 'BERJAYA',
                'latitude' => 2.646477072,
                'longitude' => 102.7564092,
            ]),
            $createRecord([
                'serial_number' => 'SG012',
                'name' => 'ROBIAH BINTI ABDUL KADIR',
                'identification_number' => '550327-01-5850',
                'gender' => 'PEREMPUAN',
                'address' => 'NO 14 JALAN MASJID KAMPUNG SPANG LOI',
                'district' => 'SEGAMAT',
                'parliament' => 'BULOH KASAP',
                'dun' => 'BULOH KASAP',
                'phone_number' => '019-7640953',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P140N01',
                'prb_serial_number' => 'JWP4019',
                'installation_status' => 'BERJAYA',
                'latitude' => 2.512251998,
                'longitude' => 102.8157944,
            ]),
            $createRecord([
                'serial_number' => 'SG013',
                'name' => 'SITI ESAH BINTI OTHMAN',
                'identification_number' => '520725-01-5576',
                'gender' => 'PEREMPUAN',
                'address' => 'KAMPUNG SPANG LOI',
                'district' => 'SEGAMAT',
                'parliament' => 'BULOH KASAP',
                'dun' => 'BULOH KASAP',
                'phone_number' => '014-2743011',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P140N01',
                'prb_serial_number' => 'JWP4023',
                'installation_status' => 'BERJAYA',
                'latitude' => 2.650134653,
                'longitude' => 102.7560471,
            ]),
            $createRecord([
                'serial_number' => 'SG014',
                'name' => 'ABDUL WAHID BIN BEKOH',
                'identification_number' => '590921-01-5251',
                'gender' => 'LELAKI',
                'address' => 'KAMPUNG KUALA PAYA BULOH KASAP',
                'district' => 'SEGAMAT',
                'parliament' => 'BULOH KASAP',
                'dun' => 'BULOH KASAP',
                'phone_number' => '010-3432900',
                'disability_category' => 'TERBARING',
                'client_type' => 'JKM',
                'oku_status' => 'YA',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P140N01',
                'prb_serial_number' => 'JWL1024',
                'installation_status' => 'BERJAYA',
                'latitude' => 2.579102895,
                'longitude' => 102.7708112,
            ]),
            $createRecord([
                'serial_number' => 'SG015',
                'name' => 'ISHAK BIN MUSTAFFA',
                'identification_number' => '930831-01-7075',
                'gender' => 'PEREMPUAN',
                'address' => '233 JALAN MUHAMMAD KAMPUNG KUALA PAYA BULOH KASAP',
                'district' => 'SEGAMAT',
                'parliament' => 'BULOH KASAP',
                'dun' => 'BULOH KASAP',
                'phone_number' => '013-7471570',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'YA',
                'age_group' => 'DEWASA',
                'parliament_dun_code' => 'P140N01',
                'prb_serial_number' => 'JDP4026',
                'installation_status' => 'BERJAYA',
                'latitude' => 2.511394534,
                'longitude' => 102.8151126,
            ]),
            $createRecord([
                'serial_number' => 'SG016',
                'name' => 'ZORKARNAIN BIN ABDULLAH',
                'identification_number' => '600701-01-5387',
                'gender' => 'LELAKI',
                'address' => '121, JALAN IBRAHIMKG. KUALA PAYA',
                'district' => 'SEGAMAT',
                'parliament' => 'BULOH KASAP',
                'dun' => 'BULOH KASAP',
                'phone_number' => '017-7313581',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P140N01',
                'prb_serial_number' => 'JWL4030',
                'installation_status' => 'BERJAYA',
                'latitude' => 2.507054373,
                'longitude' => 102.816331,
            ]),
            $createRecord([
                'serial_number' => 'SG017',
                'name' => 'AZMI BIN OTHMAN',
                'identification_number' => '580504-01-6369',
                'gender' => 'LELAKI',
                'address' => 'KAMPUNG KUALA PAYA BULOH KASAP',
                'district' => 'SEGAMAT',
                'parliament' => 'BULOH KASAP',
                'dun' => 'BULOH KASAP',
                'phone_number' => '0123342780',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P140N01',
                'prb_serial_number' => 'JWL4032',
                'installation_status' => 'BERJAYA',
                'latitude' => 2.580645871,
                'longitude' => 102.7701247,
            ]),
            $createRecord([
                'serial_number' => 'SG018',
                'name' => 'SHADAN BIN SHARIF',
                'identification_number' => '580503-01-6383',
                'gender' => 'LELAKI',
                'address' => 'NO.36, JALAN TOK SABAN KAMPUNG KUALA PAYA',
                'district' => 'SEGAMAT',
                'parliament' => 'BULOH KASAP',
                'dun' => 'BULOH KASAP',
                'phone_number' => '0179930340',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P140N01',
                'prb_serial_number' => 'JWL4033',
                'installation_status' => 'BERJAYA',
                'latitude' => 2.580352228,
                'longitude' => 102.7657362,
            ]),
            $createRecord([
                'serial_number' => 'SG019',
                'name' => 'ABU BAKAR BIN ABD RASHID',
                'identification_number' => '31128-01-1043',
                'gender' => 'LELAKI',
                'address' => 'LOT 2624 JALAN RAHMAT KAMPUNG KUALA PAYA',
                'district' => 'SEGAMAT',
                'parliament' => 'BULOH KASAP',
                'dun' => 'BULOH KASAP',
                'phone_number' => '0137743713',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'YA',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P140N01',
                'prb_serial_number' => 'JWL4034',
                'installation_status' => 'BERJAYA',
                'latitude' => 2.581642465,
                'longitude' => 102.766186,
            ]),
            $createRecord([
                'serial_number' => 'SG020',
                'name' => 'RAZAK BIN SAPAR',
                'identification_number' => '680417-01-5331',
                'gender' => 'LELAKI',
                'address' => 'LOT 356 KAMPUNG KUALA PAYA 85010 BULOH KASAP SEGAMAT',
                'district' => 'SEGAMAT',
                'parliament' => 'BULOH KASAP',
                'dun' => 'BULOH KASAP',
                'phone_number' => '0193503197',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'YA',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P140N01',
                'prb_serial_number' => 'JWL4035',
                'installation_status' => 'BERJAYA',
                'latitude' => 2.511565625,
                'longitude' => 102.8154547,
            ])
        ];

        // Kota Tinggi records
        $kotaTinggiData = [
            $createRecord([
                'serial_number' => 'KT001',
                'name' => 'KANNAN A/L KRISHNAN',
                'identification_number' => '680704-01-5561',
                'gender' => 'LELAKI',
                'address' => 'NO. 23, JALAN BELINJAU 6TAMAN KOTA JAYA',
                'district' => 'KOTA TINGGI',
                'parliament' => 'PANTI',
                'dun' => 'PANTI',
                'phone_number' => '0103645447',
                'disability_category' => 'BERTONGKAT',
                'client_type' => 'JKM',
                'oku_status' => 'YA',
                'age_group' => 'DEWASA',
                'parliament_dun_code' => 'P156N34',
                'prb_serial_number' => 'JDL2001',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.73661,
                'longitude' => 103.88413,
            ]),
            $createRecord([
                'serial_number' => 'KT002',
                'name' => 'CHIAM WEI CHIANG',
                'identification_number' => '970513-23-5137',
                'gender' => 'LELAKI',
                'address' => 'NO. 81, JALAN KUINITAMAN KOTA JAYA',
                'district' => 'KOTA TINGGI',
                'parliament' => 'PANTI',
                'dun' => 'PANTI',
                'phone_number' => '016-5199709',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'YA',
                'age_group' => 'DEWASA',
                'parliament_dun_code' => 'P156N34',
                'prb_serial_number' => 'JDL4002',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.73207,
                'longitude' => 103.88865,
            ]),
            $createRecord([
                'serial_number' => 'KT003',
                'name' => 'ABD RASHID BIN OTHMAN',
                'identification_number' => '810725-01-5715',
                'gender' => 'LELAKI',
                'address' => 'NO 95JALAN DELIMATAMAN KOTA JAYA',
                'district' => 'KOTA TINGGI',
                'parliament' => 'PANTI',
                'dun' => 'PANTI',
                'phone_number' => '019-2349600',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'YA',
                'age_group' => 'DEWASA',
                'parliament_dun_code' => 'P156N34',
                'prb_serial_number' => 'JDL4003',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.73782,
                'longitude' => 103.8863,
            ]),
            $createRecord([
                'serial_number' => 'KT004',
                'name' => 'AZMIRA NATASYA BINTI AZMI',
                'identification_number' => '030829-01-1770',
                'gender' => 'PEREMPUAN',
                'address' => 'NO 3JALAN BACANG 2TAMAN KOTA JAYA',
                'district' => 'KOTA TINGGI',
                'parliament' => 'PANTI',
                'dun' => 'PANTI',
                'phone_number' => '011-12714685',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'YA',
                'age_group' => 'DEWASA',
                'parliament_dun_code' => 'P156N34',
                'prb_serial_number' => 'JDP4005',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.73275,
                'longitude' => 103.88796,
            ]),
            $createRecord([
                'serial_number' => 'KT005',
                'name' => 'MURUGAN A/L SUBRAMANIAM',
                'identification_number' => '741011-01-6875',
                'gender' => 'LELAKI',
                'address' => 'NO 29, JALAN CERMAI,TAMAN KOTA JAYA,',
                'district' => 'KOTA TINGGI',
                'parliament' => 'PANTI',
                'dun' => 'PANTI',
                'phone_number' => '0177009047',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'YA',
                'age_group' => 'DEWASA',
                'parliament_dun_code' => 'P156N34',
                'prb_serial_number' => 'JDL4006',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.73511,
                'longitude' => 103.89465,
            ]),
            $createRecord([
                'serial_number' => 'KT006',
                'name' => 'MOHD NAZARI BIN MAHFOZ (ANAK OKU)',
                'identification_number' => '790818-01-5559',
                'gender' => 'PEREMPUAN',
                'address' => 'NO. 31,JALAN SUNGAI SIBOL 2/3, PGBF2',
                'district' => 'KOTA TINGGI',
                'parliament' => 'PANTI',
                'dun' => 'PANTI',
                'phone_number' => '012-5677973',
                'disability_category' => 'TERBARING',
                'client_type' => 'JKM',
                'oku_status' => 'YA',
                'age_group' => 'KANAK-KANAK',
                'parliament_dun_code' => 'P156N34',
                'prb_serial_number' => 'JKP1007',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.84936,
                'longitude' => 103.6362,
            ]),
            $createRecord([
                'serial_number' => 'KT007',
                'name' => 'ANUAR BIN AZIZ',
                'identification_number' => '770221-01-5945',
                'gender' => 'LELAKI',
                'address' => '21, JALAN PEDADATAMAN KOTA JAYA',
                'district' => 'KOTA TINGGI',
                'parliament' => 'PANTI',
                'dun' => 'PANTI',
                'phone_number' => '01162166533',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'YA',
                'age_group' => 'DEWASA',
                'parliament_dun_code' => 'P156N34',
                'prb_serial_number' => 'JDL4010',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.7382,
                'longitude' => 103.88996,
            ]),
            $createRecord([
                'serial_number' => 'KT008',
                'name' => 'MOHAMAD SHUKRI BIN MOHAMAD FARID',
                'identification_number' => '911026-01-5401',
                'gender' => 'LELAKI',
                'address' => 'NO 5, JALAN GELUGOR,TAMAN KOTA JAYA,',
                'district' => 'KOTA TINGGI',
                'parliament' => 'PANTI',
                'dun' => 'PANTI',
                'phone_number' => '018-4094279',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'YA',
                'age_group' => 'DEWASA',
                'parliament_dun_code' => 'P156N34',
                'prb_serial_number' => 'JDL4011',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.74038,
                'longitude' => 103.88909,
            ]),
            $createRecord([
                'serial_number' => 'KT009',
                'name' => 'MISBAH BIN KERTUBI',
                'identification_number' => '590507-01-5627',
                'gender' => 'LELAKI',
                'address' => 'NO 32, JALAN KEPAYANG,TAMAN KOTA JAYA,',
                'district' => 'KOTA TINGGI',
                'parliament' => 'PANTI',
                'dun' => 'PANTI',
                'phone_number' => '017-8263218',
                'disability_category' => 'BERTONGKAT',
                'client_type' => 'JKM',
                'oku_status' => 'YA',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P156N34',
                'prb_serial_number' => 'JWL2013',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.73972,
                'longitude' => 103.88777,
            ]),
            $createRecord([
                'serial_number' => 'KT010',
                'name' => 'KALESALVI A/P VYRAKANNU',
                'identification_number' => '631022-01-5758',
                'gender' => 'PEREMPUAN',
                'address' => 'NO. 17JALAN SUKUNTAMAN KOTA JAYA',
                'district' => 'KOTA TINGGI',
                'parliament' => 'PANTI',
                'dun' => 'PANTI',
                'phone_number' => '016-7074124',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'YA',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P156N34',
                'prb_serial_number' => 'JWP4014',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.73708,
                'longitude' => 103.88551,
            ]),
            $createRecord([
                'serial_number' => 'KT011',
                'name' => 'NG HOW PENG',
                'identification_number' => '701231-01-5499',
                'gender' => 'LELAKI',
                'address' => 'NO. 41, JALAN RAMBAI 4TAMAN KOTA JAYA',
                'district' => 'KOTA TINGGI',
                'parliament' => 'PANTI',
                'dun' => 'PANTI',
                'phone_number' => '016-7859378',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'YA',
                'age_group' => 'DEWASA',
                'parliament_dun_code' => 'P156N34',
                'prb_serial_number' => 'JDL4015',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.73963,
                'longitude' => 103.88629,
            ]),
            $createRecord([
                'serial_number' => 'KT012',
                'name' => 'SUVAPRAKASAM A/L SUPPERMANIAN',
                'identification_number' => '830417-01-6677',
                'gender' => 'LELAKI',
                'address' => 'NO.36JALAN BELIMBINGTAMAN KOTA JAYA',
                'district' => 'KOTA TINGGI',
                'parliament' => 'PANTI',
                'dun' => 'PANTI',
                'phone_number' => '016-4958021',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'YA',
                'age_group' => 'DEWASA',
                'parliament_dun_code' => 'P156N34',
                'prb_serial_number' => 'JDL4017',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.74163,
                'longitude' => 103.88973,
            ]),
            $createRecord([
                'serial_number' => 'KT013',
                'name' => 'HARICHANDRAN A/L K.SELVARAJU',
                'identification_number' => '850929-01-6599',
                'gender' => 'LELAKI',
                'address' => 'NO. 36, JALAN BELINJAU 7TAMAN KOTA JAYA',
                'district' => 'KOTA TINGGI',
                'parliament' => 'PANTI',
                'dun' => 'PANTI',
                'phone_number' => '016-7062903',
                'disability_category' => 'BERTONGKAT',
                'client_type' => 'JKM',
                'oku_status' => 'YA',
                'age_group' => 'DEWASA',
                'parliament_dun_code' => 'P156N34',
                'prb_serial_number' => 'JDL2018',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.73596,
                'longitude' => 103.88407,
            ]),
            $createRecord([
                'serial_number' => 'KT014',
                'name' => 'HASMAHZAM BINTI HUSAIN',
                'identification_number' => '530529-11-5288',
                'gender' => 'PEREMPUAN',
                'address' => 'NO.52, JALAN KUNDANGTAMAN KOTA JAYA',
                'district' => 'KOTA TINGGI',
                'parliament' => 'PANTI',
                'dun' => 'PANTI',
                'phone_number' => '0111-7981447',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'YA',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P156N34',
                'prb_serial_number' => 'JWP4019',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.73464,
                'longitude' => 103.88324,
            ]),
            $createRecord([
                'serial_number' => 'KT015',
                'name' => 'SUSILA A/P MARIAPPEN',
                'identification_number' => '570331-01-6520',
                'gender' => 'PEREMPUAN',
                'address' => 'NO 70JALAN KUNDANGTAMAN KOTA JAYA',
                'district' => 'KOTA TINGGI',
                'parliament' => 'PANTI',
                'dun' => 'PANTI',
                'phone_number' => '011-10921918',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'YA',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P156N34',
                'prb_serial_number' => 'JWP4020',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.73366,
                'longitude' => 103.8846,
            ]),
            $createRecord([
                'serial_number' => 'KT016',
                'name' => 'ALIF AZIZUL BIN MOHAMMAD',
                'identification_number' => '880218-23-5127',
                'gender' => 'LELAKI',
                'address' => 'NO 176 JALAN BELINJAUTAMAN KOTA JAYA',
                'district' => 'KOTA TINGGI',
                'parliament' => 'PANTI',
                'dun' => 'PANTI',
                'phone_number' => '017-7027510',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'YA',
                'age_group' => 'DEWASA',
                'parliament_dun_code' => 'P156N34',
                'prb_serial_number' => 'JDL4022',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.73716,
                'longitude' => 103.88294,
            ]),
            $createRecord([
                'serial_number' => 'KT017',
                'name' => 'MUHAMAD TAHIR BIN MASIMON',
                'identification_number' => '601119-01-5343',
                'gender' => 'LELAKI',
                'address' => 'NO.28, JALAN BELINJAU 4TAMAN KOTA JAYA',
                'district' => 'KOTA TINGGI',
                'parliament' => 'PANTI',
                'dun' => 'PANTI',
                'phone_number' => '012-7941296',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'YA',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P156N34',
                'prb_serial_number' => 'JWL4023',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.73711,
                'longitude' => 103.88409,
            ]),
            $createRecord([
                'serial_number' => 'KT018',
                'name' => 'ANDY PUTRA BIN ADRIALIS',
                'identification_number' => '861126-23-6233',
                'gender' => 'LELAKI',
                'address' => 'NO. 37, JALAN BERANGANTAMAN KOTA JAYA',
                'district' => 'KOTA TINGGI',
                'parliament' => 'PANTI',
                'dun' => 'PANTI',
                'phone_number' => '018-2974882',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'YA',
                'age_group' => 'DEWASA',
                'parliament_dun_code' => 'P156N34',
                'prb_serial_number' => 'JDL4024',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.74171,
                'longitude' => 103.88852,
            ]),
            $createRecord([
                'serial_number' => 'KT019',
                'name' => 'SELVIAMMA A/P DORAISAMY (ANAK OKU)',
                'identification_number' => '680425-01-6000',
                'gender' => 'PEREMPUAN',
                'address' => 'NO.48, JALAN MANGGIS 2,TAMAN KOTA JAYA,',
                'district' => 'KOTA TINGGI',
                'parliament' => 'PANTI',
                'dun' => 'PANTI',
                'phone_number' => '016-7469860',
                'disability_category' => 'TERBARING',
                'client_type' => 'JKM',
                'oku_status' => 'YA',
                'age_group' => 'DEWASA',
                'parliament_dun_code' => 'P156N34',
                'prb_serial_number' => 'JDP1025',
                'installation_status' => 'BERJAYA',
                'latitude' => 1.73376,
                'longitude' => 103.88736,
            ])
        ];

        // Kluang records
        $kluangData = [
            $createRecord([
                'serial_number' => 'KL001',
                'name' => 'MOHD SALLEH BIN A. KARIM',
                'identification_number' => '580225-01-5963',
                'gender' => 'LELAKI',
                'address' => 'NO 44 JLN DATO ZAIN KG BENTONG DALAM',
                'district' => 'KLUANG',
                'parliament' => 'KLUANG',
                'dun' => 'MAHKOTA',
                'phone_number' => '012-7858212',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P152N29',
                'prb_serial_number' => 'JWL4001',
                'installation_status' => 'BERJAYA',
                'latitude' => 2.056248,
                'longitude' => 103.295256,
            ]),
            $createRecord([
                'serial_number' => 'KL002',
                'name' => 'SANIAH BINTI OTHMAN',
                'identification_number' => '641123-01-6600',
                'gender' => 'PEREMPUAN',
                'address' => 'NO 77 JLN HASSAN KG BENTONG DALAM',
                'district' => 'KLUANG',
                'parliament' => 'KLUANG',
                'dun' => 'MAHKOTA',
                'phone_number' => '018-7634038',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P152N29',
                'prb_serial_number' => 'JWP4002',
                'installation_status' => 'BERJAYA',
                'latitude' => 2.056246,
                'longitude' => 103.295305,
            ]),
            $createRecord([
                'serial_number' => 'KL003',
                'name' => 'HASSAN BIN SAPON',
                'identification_number' => '540220-01-5843',
                'gender' => 'LELAKI',
                'address' => 'NO 73 JLN HASSAN KG BENTONG DALAM',
                'district' => 'KLUANG',
                'parliament' => 'KLUANG',
                'dun' => 'MAHKOTA',
                'phone_number' => '010-4184303',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P152N29',
                'prb_serial_number' => 'JWL4003',
                'installation_status' => 'BERJAYA',
                'latitude' => 2.053592,
                'longitude' => 103.294625,
            ]),
            $createRecord([
                'serial_number' => 'KL004',
                'name' => 'SABARIAH BINTI BARJURI',
                'identification_number' => '561009-01-5082',
                'gender' => 'PEREMPUAN',
                'address' => 'NO 10 JLN TENGAH KG BENTONG DALAM',
                'district' => 'KLUANG',
                'parliament' => 'KLUANG',
                'dun' => 'MAHKOTA',
                'phone_number' => '011-11901145',
                'disability_category' => 'BERTONGKAT',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P152N29',
                'prb_serial_number' => 'JWP2004',
                'installation_status' => 'BERJAYA',
                'latitude' => 2.053779,
                'longitude' => 103.296351,
            ]),
            $createRecord([
                'serial_number' => 'KL005',
                'name' => 'KHATIJAH BIN DOL BASAR',
                'identification_number' => '560709-01-5206',
                'gender' => 'PEREMPUAN',
                'address' => 'NO 40 JLN DATO ZAIN KG BENTONG DALAM',
                'district' => 'KLUANG',
                'parliament' => 'KLUANG',
                'dun' => 'MAHKOTA',
                'phone_number' => '011-56807470',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P152N29',
                'prb_serial_number' => 'JDL4005',
                'installation_status' => 'BERJAYA',
                'latitude' => 2.048201,
                'longitude' => 103.295276,
            ]),
            $createRecord([
                'serial_number' => 'KL006',
                'name' => 'JAAFAR BIN ESA',
                'identification_number' => '720305-01-5277',
                'gender' => 'LELAKI',
                'address' => '145, KG TENGAH DALAM, 86000 KLUANG',
                'district' => 'KLUANG',
                'parliament' => 'KLUANG',
                'dun' => 'MAHKOTA',
                'phone_number' => '017-8245105',
                'disability_category' => 'OKU (LAIN-LAIN KEUPAYAAN)',
                'client_type' => 'JKM',
                'oku_status' => '4 ORANG (1 OKU, 2 MASALAH KESIHATAN)',
                'age_group' => 'DEWASA',
                'parliament_dun_code' => 'P152N29',
                'prb_serial_number' => 'JDL4006',
                'installation_status' => 'BERJAYA',
                'latitude' => 2.0592536,
                'longitude' => 103.3426543,
            ]),
            $createRecord([
                'serial_number' => 'KL007',
                'name' => 'SULAIMAN BIN OMAR (ANAK) OMAR BIN URIP (BAPA)',
                'identification_number' => '510724-01-5911',
                'gender' => 'LELAKI',
                'address' => '202A, KG TENGAH DALAM, 86000 KLUANG, JOHOR',
                'district' => 'KLUANG',
                'parliament' => 'KLUANG',
                'dun' => 'MAHKOTA',
                'phone_number' => '013-9014011',
                'disability_category' => 'WARGA EMAS (PENYAKIT 3 SERANGKAI)',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P152N29',
                'prb_serial_number' => 'JWL4007',
                'installation_status' => 'BERJAYA',
                'latitude' => 2.071623,
                'longitude' => 103.334249,
            ]),
            $createRecord([
                'serial_number' => 'KL008',
                'name' => 'AHMAD BIN AZIZ',
                'identification_number' => '550107-02-5301',
                'gender' => 'LELAKI',
                'address' => 'NO. 200-D, LORONG JAYA, KG TENGAH DALAM, 86000 KLUANG JOHOR',
                'district' => 'KLUANG',
                'parliament' => 'KLUANG',
                'dun' => 'MAHKOTA',
                'phone_number' => '019-2577486',
                'disability_category' => 'WARGA EMAS (PENYAKIT DARAH TINGGI)',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P152N29',
                'prb_serial_number' => 'JWL4008',
                'installation_status' => 'BERJAYA',
                'latitude' => 2.072337,
                'longitude' => 103.334487,
            ]),
            $createRecord([
                'serial_number' => 'KL009',
                'name' => 'RAHMAH BINTI RETHUAN',
                'identification_number' => '541113-01-5762',
                'gender' => 'PEREMPUAN',
                'address' => 'NO. 200-2, LORONG JAYA, KG TENGAH DALAM,86000 KLUANG JOHOR',
                'district' => 'KLUANG',
                'parliament' => 'KLUANG',
                'dun' => 'MAHKOTA',
                'phone_number' => '017-7665605',
                'disability_category' => 'WARGA EMAS',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P152N29',
                'prb_serial_number' => 'JWP4009',
                'installation_status' => 'BERJAYA',
                'latitude' => 2.070616,
                'longitude' => 103.334528,
            ]),
            $createRecord([
                'serial_number' => 'KL010',
                'name' => 'MASAJI BIN SUKIMI',
                'identification_number' => '540311-01-5945',
                'gender' => 'LELAKI',
                'address' => 'KAMPUNG TENGAH DALAM, 86000 KLUANG JOHOR',
                'district' => 'KLUANG',
                'parliament' => 'KLUANG',
                'dun' => 'MAHKOTA',
                'phone_number' => '013-7547656',
                'disability_category' => 'ISTERI TERLANTAR',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P152N29',
                'prb_serial_number' => 'JWL1010',
                'installation_status' => 'BERJAYA',
                'latitude' => 2.0592536,
                'longitude' => 103.3426543,
            ]),
            $createRecord([
                'serial_number' => 'KL011',
                'name' => 'ABD KAMIT BIN MOHD SITOL',
                'identification_number' => '560611-01-6963',
                'gender' => 'LELAKI',
                'address' => 'NO. 25, JLN 1, KG PALEMBANG BARU, 86000 KLUANG',
                'district' => 'KLUANG',
                'parliament' => 'KLUANG',
                'dun' => 'MAHKOTA',
                'phone_number' => '019-7678240',
                'disability_category' => 'WARGA EMAS (TINGGAL BERDUA DENGAN ISTERI)',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P152N29',
                'prb_serial_number' => 'JWL4011',
                'installation_status' => 'BERJAYA',
                'latitude' => 2.075796,
                'longitude' => 103.303792,
            ]),
            $createRecord([
                'serial_number' => 'KL012',
                'name' => 'ABDUL RANI BIN BABA',
                'identification_number' => '570601-04-5007',
                'gender' => 'LELAKI',
                'address' => 'NO 12, JALAN KG PALEMBANG BARU, 86000 KLUANG',
                'district' => 'KLUANG',
                'parliament' => 'KLUANG',
                'dun' => 'MAHKOTA',
                'phone_number' => '013-7064794',
                'disability_category' => 'WARGA EMAS (11 ORANG)',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P152N29',
                'prb_serial_number' => 'JWL4012',
                'installation_status' => 'BERJAYA',
                'latitude' => 2.074038,
                'longitude' => 103.302730,
            ]),
            $createRecord([
                'serial_number' => 'KL013',
                'name' => 'AZMI BIN MUSTAPHA (MENINGGAL DUNIA) MANISAH BINTI SITOL (ISTERI)',
                'identification_number' => '-',
                'gender' => 'LELAKI PEREMPUAN',
                'address' => 'P40, JALAN 1, KG PALEMBANG BARU, 86000 KLUANG',
                'district' => 'KLUANG',
                'parliament' => 'KLUANG',
                'dun' => 'MAHKOTA',
                'phone_number' => '017-7906340',
                'disability_category' => 'WARGA EMAS (8 ORANG)',
                'client_type' => 'JKM',
                'oku_status' => 'PENYAKIT 3 SERANGKAI (JANTUNG, KENCING MANIS DAN DARAH TINGGI)',
                'age_group' => '',
                'parliament_dun_code' => 'P152N29',
                'prb_serial_number' => 'JWL4013',
                'installation_status' => 'BERJAYA',
                'latitude' => 2.075793,
                'longitude' => 103.303042,
            ]),
            $createRecord([
                'serial_number' => 'KL014',
                'name' => 'IBRAHIM BIN SALLEH',
                'identification_number' => '630521-01-5205',
                'gender' => 'LELAKI',
                'address' => 'NO. 10, LORONG BALAIRAYA 3, KG PALEMBANG LAMA, 86000 KLUANG',
                'district' => 'KLUANG',
                'parliament' => 'KLUANG',
                'dun' => 'MAHKOTA',
                'phone_number' => '011-62171792',
                'disability_category' => 'WARGA EMAS (4 ORANG)',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P152N29',
                'prb_serial_number' => 'JWL4014',
                'installation_status' => 'BERJAYA',
                'latitude' => 2.059799,
                'longitude' => 103.316585,
            ]),
            $createRecord([
                'serial_number' => 'KL015',
                'name' => 'JAWIYSAH BINTI SARBNI',
                'identification_number' => '641011-01-6076',
                'gender' => 'PEREMPUAN',
                'address' => 'NO. 37, JLN 1, KG PALEMBANG BARU',
                'district' => 'KLUANG',
                'parliament' => 'KLUANG',
                'dun' => 'MAHKOTA',
                'phone_number' => '019-7533457',
                'disability_category' => 'WARGA EMAS (2 ORANG)',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'WARGA EMAS',
                'parliament_dun_code' => 'P152N29',
                'prb_serial_number' => 'JWP4015',
                'installation_status' => 'BERJAYA',
                'latitude' => 2.076129,
                'longitude' => 103.302745,
            ]),
            $createRecord([
                'serial_number' => 'KL016',
                'name' => 'MUAIMIN BIN AZLI MUAIMAN BIN AZLI',
                'identification_number' => '110418-01-1733',
                'gender' => 'LELAKI',
                'address' => 'NO 7, RUMAH SPKR KG CONTOH KM 32 JALAN MERSING 86700 KAHANG',
                'district' => 'KLUANG',
                'parliament' => 'SEMBRONG',
                'dun' => 'KAHANG',
                'phone_number' => '013-6092066',
                'disability_category' => 'BERKERUSI RODA BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'OKU FIZIKAL (OSTOMY)',
                'age_group' => 'KANAK-KANAK',
                'parliament_dun_code' => 'P153N31',
                'prb_serial_number' => 'JKL3001',
                'installation_status' => 'BERJAYA',
                'latitude' => 2.204594,
                'longitude' => 103.530604,
            ]),
            $createRecord([
                'serial_number' => 'KL017',
                'name' => 'FARIDAH BINTI SALIM',
                'identification_number' => '780412-01-5242',
                'gender' => 'PEREMPUAN',
                'address' => 'LOT 3851 KG CONTOH KAHANG 86700 KAHANG KLUANG',
                'district' => 'KLUANG',
                'parliament' => 'SEMBRONG',
                'dun' => 'KAHANG',
                'phone_number' => '019-7203979',
                'disability_category' => 'TERBARING',
                'client_type' => 'JKM',
                'oku_status' => 'TIDAK',
                'age_group' => 'DEWASA',
                'parliament_dun_code' => 'P153N31',
                'prb_serial_number' => 'JDP1002',
                'installation_status' => 'BERJAYA',
                'latitude' => 2.204305,
                'longitude' => 103.530634,
            ]),
            $createRecord([
                'serial_number' => 'KL018',
                'name' => 'ROSLIHA BINTI YUSOF (BERNIAGA KECIL-KECILAN)',
                'identification_number' => '730416-03-5050',
                'gender' => 'PEREMPUAN',
                'address' => 'NO 10 KG CONTOH BT 22, 86700 KAHANG KLUANG',
                'district' => 'KLUANG',
                'parliament' => 'SEMBRONG',
                'dun' => 'KAHANG',
                'phone_number' => '010-8039383',
                'disability_category' => 'BERTONGKAT',
                'client_type' => 'JKM',
                'oku_status' => 'OKU FIZIKAL (KAKI KANAN KODONG)',
                'age_group' => 'DEWASA',
                'parliament_dun_code' => 'P153N31',
                'prb_serial_number' => 'JDP2003',
                'installation_status' => 'BERJAYA',
                'latitude' => 2.202512,
                'longitude' => 103.531111,
            ]),
            $createRecord([
                'serial_number' => 'KL019',
                'name' => 'KAMALUDIN BIN AMAN (BERNIAGA KECIL-KECILAN)',
                'identification_number' => '720627-01-6109',
                'gender' => 'LELAKI',
                'address' => 'NO 10, KG CONTOH BT 22 86700 KAHANG KLUANG',
                'district' => 'KLUANG',
                'parliament' => 'SEMBRONG',
                'dun' => 'KAHANG',
                'phone_number' => '013-7177428',
                'disability_category' => 'BERTONGKAT',
                'client_type' => 'JKM',
                'oku_status' => 'OKU FIZIKAL (KAKI KANAN KODONG)',
                'age_group' => 'DEWASA',
                'parliament_dun_code' => 'P153N31',
                'prb_serial_number' => 'JDL2004',
                'installation_status' => 'BERJAYA',
                'latitude' => 2.202512,
                'longitude' => 103.531111,
            ]),
            $createRecord([
                'serial_number' => 'KL020',
                'name' => 'ISKANDAR BIN ABDULLAH SANI (BEKERJA SENDIRI)',
                'identification_number' => '780123-01-5289',
                'gender' => 'LELAKI',
                'address' => 'JPB 24-14, RUMAH PPRT NO 9, JALAN MERSING BT 22, KG CONTOH, 86700 KAHANG, KLUANG',
                'district' => 'KLUANG',
                'parliament' => 'SEMBRONG',
                'dun' => 'KAHANG',
                'phone_number' => '017-7401695',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'OKU FIZIKAL (KAKI KANAN, BAHU TIDAK BOLEH ANGKAT)',
                'age_group' => 'DEWASA',
                'parliament_dun_code' => 'P153N31',
                'prb_serial_number' => 'JDL4005',
                'installation_status' => 'BERJAYA',
                'latitude' => 2.2046340,
                'longitude' => 103.5264810,
            ]),
            $createRecord([
                'serial_number' => 'KL021',
                'name' => 'RASSYAIDATUL AKMAR BINTI ABD HALIM',
                'identification_number' => '870803-23-5516',
                'gender' => 'PEREMPUAN',
                'address' => 'LOT 3828 KG CONTOH 86700 KAHANG KLUANG',
                'district' => 'KLUANG',
                'parliament' => 'SEMBRONG',
                'dun' => 'KAHANG',
                'phone_number' => '011-14987262',
                'disability_category' => '-',
                'client_type' => 'JKM',
                'oku_status' => 'OKU FIZIKAL',
                'age_group' => 'DEWASA',
                'parliament_dun_code' => 'P153N31',
                'prb_serial_number' => 'JDP4006',
                'installation_status' => 'BERJAYA',
                'latitude' => 2.203462,
                'longitude' => 103.530851,
            ]),
            $createRecord([
                'serial_number' => 'KL022',
                'name' => 'ROZILAH BINTI SARMIN (TIDAK BEKERJA)',
                'identification_number' => '931112-01-6724',
                'gender' => 'PEREMPUAN',
                'address' => 'NO 48,TL KC9 KAMPUNG CONTOH BATU 22 JALAN MERSING 86700 KAHANG JOHOR',
                'district' => 'KLUANG',
                'parliament' => 'SEMBRONG',
                'dun' => 'KAHANG',
                'phone_number' => '019-7252726',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'OKU LEMBAM',
                'age_group' => 'DEWASA',
                'parliament_dun_code' => 'P153N31',
                'prb_serial_number' => 'JDP4007',
                'installation_status' => 'BERJAYA',
                'latitude' => 2.197300,
                'longitude' => 103.526182,
            ]),
            $createRecord([
                'serial_number' => 'KL023',
                'name' => 'ROSNAH BINTI SUKIRAN (TIDAK BEKERJA)',
                'identification_number' => '850320-06-5606',
                'gender' => 'PEREMPUAN',
                'address' => 'NO2 RUMAH PBR KG .CONTOH BATU 22 86700 KLUANG JOHOR',
                'district' => 'KLUANG',
                'parliament' => 'SEMBRONG',
                'dun' => 'KAHANG',
                'phone_number' => '013-9413435',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'OKU LEMBAM',
                'age_group' => 'DEWASA',
                'parliament_dun_code' => 'P153N31',
                'prb_serial_number' => 'JDP4008',
                'installation_status' => 'BERJAYA',
                'latitude' => 2.195466,
                'longitude' => 103.530420,
            ]),
            $createRecord([
                'serial_number' => 'KL024',
                'name' => 'NORHASIDAH BINTI PUNIRAN (BEKERJA)',
                'identification_number' => '000215-01-0688',
                'gender' => 'PEREMPUAN',
                'address' => 'NO 4 RUMAH PBR KG CONTOH BATU 22 ,86700 KLUANG JOHOR',
                'district' => 'KLUANG',
                'parliament' => 'SEMBRONG',
                'dun' => 'KAHANG',
                'phone_number' => '019-2950713',
                'disability_category' => 'BOLEH BERJALAN',
                'client_type' => 'JKM',
                'oku_status' => 'OKU LEMBAM',
                'age_group' => 'DEWASA',
                'parliament_dun_code' => 'P153N31',
                'prb_serial_number' => 'JDP4009',
                'installation_status' => 'BERJAYA',
                'latitude' => 2.195607,
                'longitude' => 103.530189,
            ]),
        ];

        // Combine all data
        $this->data = array_merge(
            $batuPahatData,
            $segamatData ?? [],
            $kotaTinggiData ?? [],
            $kluangData ?? []
        );
        
        // Clean and validate data before insertion
        $cleanData = array_filter(array_map([$this, 'cleanRecord'], $this->data));
        
        // Check for duplicate serial_number values before inserting
        $serials = array_column($cleanData, 'serial_number');
        $duplicates = array_unique(array_diff_assoc($serials, array_unique($serials)));
        if (!empty($duplicates)) {
            $this->command->error('Duplicate serial_number values found:');
            foreach ($duplicates as $dup) {
                $this->command->error($dup);
            }
            exit(1); // Stop seeding if duplicates found
        }
        // Check for duplicate identification_number values before inserting
        $ids = array_column($cleanData, 'identification_number');
        $idDuplicates = array_unique(array_diff_assoc($ids, array_unique($ids)));
        if (!empty($idDuplicates)) {
            $this->command->error('Duplicate identification_number values found:');
            foreach ($idDuplicates as $dup) {
                $this->command->error($dup);
            }
            exit(1); // Stop seeding if duplicates found
        }
        // Insert all data in chunks to avoid memory issues
        foreach (array_chunk($cleanData, 50) as $chunk) {
            try {
                DB::table('vulnerable_groups')->insert($chunk);
            } catch (\Exception $e) {
                $this->command->error('Error inserting records: ' . $e->getMessage());
                // Try to insert records one by one to identify the problematic one
                foreach ($chunk as $record) {
                    try {
                        DB::table('vulnerable_groups')->insert($record);
                    } catch (\Exception $e) {
                        $this->command->error('Failed to insert record: ' . json_encode($record));
                        $this->command->error('Error: ' . $e->getMessage());
                    }
                }
            }
        }
    }
}
